name: wechat
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.6.3
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_notification_channel: ^2.0.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  image_picker: ^1.0.5
  mime: ^1.0.4
  uuid: ^4.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
