// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQgxnFLnjjSGMG1Sw8fmvx8mBJlm87T4',
    appId: '1:983363030733:web:a8e1656aed50d56213a384',
    messagingSenderId: '983363030733',
    projectId: 'wechat-1e036',
    authDomain: 'wechat-1e036.firebaseapp.com',
    storageBucket: 'wechat-1e036.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_QTmTHZz6sLWtqruf1IlsXV2mypQAow',
    appId: '1:983363030733:android:0ce322ef35edb3c013a384',
    messagingSenderId: '983363030733',
    projectId: 'wechat-1e036',
    storageBucket: 'wechat-1e036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbavdHMDscPRsNvtGY-H7eEEZAfuNraw',
    appId: '1:983363030733:ios:9a103f455389980a13a384',
    messagingSenderId: '983363030733',
    projectId: 'wechat-1e036',
    storageBucket: 'wechat-1e036.appspot.com',
    androidClientId: '983363030733-o3fuhopkgs3batjbqm2lgd1vspugu6kj.apps.googleusercontent.com',
    iosClientId: '983363030733-q0njb8vm6p13tnv52u8epda8lmfnob8f.apps.googleusercontent.com',
    iosBundleId: 'com.devkotes.wechat',
  );
}
