// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotwraNETChrvxKf6yzYNc8NZLWGgaJ1k',
    appId: '1:641007221923:web:8b3378fe33579cfc3b5316',
    messagingSenderId: '641007221923',
    projectId: 'wechat-kedi',
    authDomain: 'wechat-kedi.firebaseapp.com',
    storageBucket: 'wechat-kedi.appspot.com',
    measurementId: 'G-HHD6QPDX1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwbmpdTV8rHR0tDZp8jNW_-fWKkfRGiY',
    appId: '1:641007221923:android:e462f83ec2c142ab3b5316',
    messagingSenderId: '641007221923',
    projectId: 'wechat-kedi',
    storageBucket: 'wechat-kedi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-C0gvsOscKS8egOscVrKRQWRDJE9QxA',
    appId: '1:641007221923:ios:8aa09d4193bd2e7b3b5316',
    messagingSenderId: '641007221923',
    projectId: 'wechat-kedi',
    storageBucket: 'wechat-kedi.appspot.com',
    iosClientId: '641007221923-nlm7qnad2t70g3tm9jmp0jjiem4cpkf8.apps.googleusercontent.com',
    iosBundleId: 'com.devkotes.wechat',
  );
}
